### ISSUE TITLE
HDA support for CS8409/CS42L42 codecs

### ISSUE THREAD

**Issue by vicamo** [CirrusLogic/product-support#1]
With patch from https://github.com/CirrusLogic/product-support/blob/cs8409_hda/dell/hda/5.10.7/patch_cirrus.patch, a Ubuntu kernel built and is available in https://launchpad.net/~vicamo/+archive/ubuntu/ppa-1913523 along with the corresponding git branch. From that a few couple of logs captured for further analysis:
* [alsa-info without patch](https://github.com/CirrusLogic/product-support/files/5925702/alsa-info.5.10.0-1013-oem.gz)
* [alsa-info with patch](https://github.com/CirrusLogic/product-support/files/5925703/alsa-info.5.10.0-2014-oem.gz)
* [dmesg without patch](https://github.com/CirrusLogic/product-support/files/5925704/dmesg.5.10.0-1013-oem.gz)
* [dmesg with patch](https://github.com/CirrusLogic/product-support/files/5925705/dmesg.5.10.0-2014-oem.gz)

However, it seems something is missing on a Dell Cyborg such that ALSA still gets a dummy output only. Please help.

**Comment by snake0x65** [comment]
Hi You-Sheng Yang,
I see the problem now, we have no matching entry in PCI_QUIRK table for this model, so even though driver boots OK, but pins configuration left with default values. I am fixing this table now. Will upload patch as soon as possible. 
Can I ask you to retest with additional change in /etc/modprobe.d/alsa-base.conf file.
Please add next string to the end of the file and reboot.

options snd-hda-intel model=bulleseye

It should pick up correct fixup table and get outputs.

**Comment by snake0x65** [comment]
I see now you are using Dell Cyborg platform, so the sting should be:
 
options snd-hda-intel model=cyborg

But it doesn't really matter, as all 3 fix-up tables for all 3 variants Bullseye, Warlock and Cyborg currently identical.

**Comment by snake0x65** [comment]
Fixed SND_PCI_QUIRK tables, should now fix dummy outputs issue.
!!!!!! NOTE !!!!!!
If you are patching clean kernel, then please do:
File :  patch_cirrus-04-02-21.patch
Path : ./sound/pci/hda
Cmd  : patch < patch_cirrus-04-02-21.patch
If you already have previous patch in place, then, please, use delta patch:
File :  patch_cirrus-fix-001.patch
Path : ./sound/pci/hda
Cmd  : patch < patch_cirrus-fix-001.patch
Full sound/pci/hds source code with latest patch is also updated.
File: patch_cirrus.tar.gz

**Comment by vicamo** [comment]
@snake0x65 Thank you. Verified the second revision with basic audio io. Kernel being pushed to the same PPA for your verification if necessary.
* [alsa-info.5.10.0-2014-oem.rev-2.gz](https://github.com/CirrusLogic/product-support/files/5930339/alsa-info.5.10.0-2014-oem.rev-2.gz)
* [dmesg.5.10.0-2014-oem.rev-2.gz](https://github.com/CirrusLogic/product-support/files/5930340/dmesg.5.10.0-2014-oem.rev-2.gz)

**Comment by fspkwon** [comment]
what about APPLE Platform patches, and BSD Support?
where would I start? Theres a Apple Patcher snd-hda-macbookpro on davidjo's repository...
and what im doing a.t.m. is learning from AI to try to get any useful information from hooking a debug hda kext
on macOS Tahoe.. to get any kind of message logs related to HDA Verbs..

**Comment by fspkwon** [comment]
Thats actually genius, LOST audio after resuming from suspend so say im in a debugging session running logs on THIS iMac .. would it be suspending the Card and Resuming the card... and we can see this happening in the Log Viewer?
