### ISSUE TITLE
Got dummy output in Dell Cyborg

### ISSUE THREAD

**Issue by chih-canonical** [CirrusLogic/product-support#10]
We were trying to apply the kernel developed for Dell Bullseye before to Cyborg and found that most audio functions are not working.

This Cyborg machine is said to be equipped with the Intel DMIC technology:

  snd_hda_intel 0000:00:1f.3: DSP detected with PCI class/subclass/prog-if info 0x040380
  snd_hda_intel 0000:00:1f.3: Digital mics found on Skylake+ platform, using SOF driver

Can you help review the attached log please?

[alsa-info.202104-28910.5.10.txt](https://github.com/CirrusLogic/product-support/files/6309587/alsa-info.202104-28910.5.10.txt)

**Comment by stefdb** [comment]
@chih-canonical There doesn't seem anything out of the ordinary in the log attached above. The driver is probed, and the log shows all the expected mixer controls, and aplay has devices. In settings, I have real devices, and am able to playback/record audio.

I've run alsa-info.sh locally on the Cyborg I have here, and the log looks almost identical.
I've attached it here for comparison:
[alsa-info.txt](https://github.com/CirrusLogic/product-support/files/6310449/alsa-info.txt)

Though it does seem like I have both a different SKU (0A7E vs 0AE0), and different firmware version (66.2.6 vs 0.3.1), but the driver seems to probe in both logs:

[    3.979957] snd_hda_codec_cirrus ehdaudio0D0: autoconfig for CS8409: line_outs=1 (0x2c/0x0/0x0/0x0/0x0) type:speaker
[    3.979959] snd_hda_codec_cirrus ehdaudio0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[    3.979960] snd_hda_codec_cirrus ehdaudio0D0:    hp_outs=1 (0x24/0x0/0x0/0x0/0x0)
[    3.979960] snd_hda_codec_cirrus ehdaudio0D0:    mono: mono_out=0x0
[    3.979961] snd_hda_codec_cirrus ehdaudio0D0:    inputs:
[    3.979962] snd_hda_codec_cirrus ehdaudio0D0:      Internal Mic=0x44
[    3.979963] snd_hda_codec_cirrus ehdaudio0D0:      Mic=0x34

**Comment by chih-canonical** [comment]
@stefdb, please see our developer's comments below:

"
On BIOS 0.3.1, the cirrus logic is probed, but the driver selects sof-
hda-generic-idisp-2ch.tplg as the topology file, then it fails to report
Speaker and DMIC pcm, but only has HDMI pcm. I don't think cirrus logic
has any further action before we receive the latest workable BIOS. I
have to check why it loads sof-hda-generic-idisp-2ch.tplg but not sof-
hda-generic-2ch.tplg as previous DMIC platform.
"

**Comment by chih-canonical** [comment]
We tried the latest 0.3.4 BIOS and found it fixed the issue.  I think we can close this issue, thank you for the support.
