### ISSUE TITLE
Cracking noises appears in built-in speaker when output volume is set >80% 

### ISSUE THREAD

**Issue by chih-canonical** [CirrusLogic/product-support#11]
In the Dell bullseye Intel and AMD platforms, we noticed some cracking noises in audio playback from the built-in speaker when the volume is set to >80%

Can you help check if you also notice it in your Dell Bullseye samples please?

**Comment by chih-canonical** [comment]
The latest Bullseye image can be downloaded from https://files.support.canonical.com/f/f485b4c03fc1c11d

**Comment by snake0x65** [comment]
@chih-canonical , please use patch: https://github.com/CirrusLogic/product-support/blob/cs8409_hda/dell/hda/5.10.7/0001-ALSA-hda-cirrus-Add-14dB-attenuation-using-CS8409-EQ.patch , we believe it should fix an issue.

**Comment by chih-canonical** [comment]
@snake0x65 

Here are the comments on the patch from our developer for your reference:
"
Test kernels available in
https://launchpad.net/~vicamo/+archive/ubuntu/ppa-1924997, version
5.10.0-2023.24+lp1924997.1.cirrus.crack.sound .

However, I'd say:
1. I do hear crack sound in the right channel before and after the fix applied,

2. I don't feel it's any a bit better for the left channel with the fix
applied.

3. We don't have a acoustic lab to perform precise measurements on the
differences, so I'll let you decide (and maybe please give us comparison
results/tools/procedures if possible).
"

But I believe you did notice some improvements before and after applying the patch in your Bullseye unit, correct?

**Comment by hhyshw** [comment]
@snake0x65 @chih-canonical 
    Can you use the software APPS of phone to detect the "Noise Detect Analyze" that we can know clearly the issue?

**Comment by chih-canonical** [comment]
@hhyshw @snake0x65 Please refer to the recording file in the attachment. It was recorded at 100% volume in our Bullseye AMD unit. 
[Recording.zip](https://github.com/CirrusLogic/product-support/files/6341751/Recording.zip)

**Comment by snake0x65** [comment]
@chih-canonical , please make sure that the default sample rate is set to 48,000. It sounds like an issue in https://github.com/CirrusLogic/product-support/issues/7

**Comment by snake0x65** [comment]
@chih-canonical , new patch available: https://github.com/CirrusLogic/product-support/blob/cs8409_hda/dell/hda/5.10.7/0001-ALSA-hda-cirrus-Use-CS8409-Equalizer-to-fix-abnormal.patch 
Please, make sure, you have default sample rate set to 48,000.
Thanks

**Comment by chih-canonical** [comment]
A test kernel based on the latest patch is available at
https://launchpad.net/~vicamo/+archive/ubuntu/ppa-1924997, version
5.10.0-2023.24+lp1924997.2.cirrus.crack.sound .

This version seems promising for me. Again, since this issue was filed
by ODM, we'll need their confirmation if the audio quality with this fix
meets their expectation.

**Comment by snake0x65** [comment]
@chih-canonical , we have managed to reproduce this issue on one of our Bullseye TGL laptops, and we can confirm that the latest patch has fixed an issue.  As soon as this is confirmed from ODM side we will release the upstream patch.

**Comment by snake0x65** [comment]
@chih-canonical , ODM confirmed the issue has been fixed, we will upstream and let you know.

**Comment by snake0x65** [comment]
@chih-canonical , fix patch has been submitted for upstream review.

**Comment by chih-canonical** [comment]
@snake0x65 Can you point us to the link to the submission please? Is it exactly the same as https://github.com/CirrusLogic/product-support/blob/cs8409_hda/dell/hda/5.10.7/0001-ALSA-hda-cirrus-Use-CS8409-Equalizer-to-fix-abnormal.patch?

**Comment by snake0x65** [comment]
@chih-canonical , yes, this is exactly the same patch. https://patchwork.kernel.org/project/alsa-devel/patch/20210424143244.639125-3-vitalyr@opensource.cirrus.com/  patch is under review, we need to answer maintainer questions.

**Comment by snake0x65** [comment]
@chih-canonical patch upstreamed: https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/commit/?id=45b14fe200ba0611b6c3874aa5bba584dc979fb9

**Comment by chih-canonical** [comment]
@snake0x65 The Dell also reported this issue on their Warlock platform. Can you help extend your patch to support that platform please?
