### ISSUE TITLE
Sound recording does not work using the internal Mic

### ISSUE THREAD

**Issue by chih-canonical** [CirrusLogic/product-support#2]
We applied the driver patch - https://github.com/CirrusLogic/product-support/tree/cs8409_hda to the Ubuntu 5.10 kernel (the patched kernel can be found in https://launchpad.net/~vicamo/+archive/ubuntu/ppa-1913523 and tested it on a target Dell machine and found the audio recording feature (via internal Mic) does not work.  Can you help take a look please?

You can find the alsa-info output from the failed unit in https://files.support.canonical.com/f/07c6abf797e8a89b

**Comment by snake0x65** [comment]
Hello,

Please find new patch patch_cirrus_22-Feb-2021.patch, this patch should fix DMIC capture issue. Please, note, this is full patch and should be applied on clean kernel code. Previous patches are deprecated.  Also, you will need to set default sample rate for pulseaudio:
file: /etc/pulse/daemon.conf
default-sample-rate = 48000

**Comment by chih-canonical** [comment]
@sanke0x65, the basic audio recording function is confirmed to work after applying the suggested patch to the target Dell system. Thanks.

**Comment by hhyshw** [comment]
@chih-canonical 
    This is Karl from Cirrus Logic.  Do we have tried with headset playback or headset mic record ?
Thanks
Karl Sun

**Comment by chih-canonical** [comment]
@Kai, good reminder! We tried the headset on the target Dell machine and found the audio playback and recording via headset worked fine. 

However, most audio features stop working after system resuming from suspend. I will report a new bug about it.

**Comment by snake0x65** [comment]
I am closing this issue now, as we have new ticket related to suspend()/resume() issue on Bullseye platform.
