### ISSUE TITLE
Lost most audio functions after resuming from suspend

### ISSUE THREAD

**Issue by chih-canonical** [CirrusLogic/product-support#3]
With the following kernel in the PPA: 5.10.0-2014.15+lp1913523.cirrus.CS8409.CS42L42.3 built from patch - patch_cirrus_22-Feb-2021.patch on the target Dell system, we found most audio functions stop working (playback and recording, via the bulit-in devices or a headset) after resuming from suspend. 

The also-info output from the failed unit can be found in https://files.support.canonical.com/f/369ea3d0ceafee42

**Comment by chih-canonical** [comment]
Here is the dmesg output from the failed unit: https://files.support.canonical.com/f/f9e9915edddd225a

**Comment by snake0x65** [comment]
For some reason, I cannot access these links : 
https://files.support.canonical.com/f/369ea3d0ceafee42
https://files.support.canonical.com/f/f9e9915edddd225a
I can see blank pages there, could you, please double check and maybe attach dmesg and alsa logs to this ticket.
We have only Cyborg models here at the moment, Intel and AMD variants. With patch provided we do not have failure after suspend. But I will double check and update you asap.

**Comment by chih-canonical** [comment]
[dell-bullseye-cirrus-resume-dmesg.log](https://github.com/CirrusLogic/product-support/files/6027868/dell-bullseye-cirrus-resume-dmesg.log)
[dell-bullseye-cirrus-resume-alsa-info.log](https://github.com/CirrusLogic/product-support/files/6027869/dell-bullseye-cirrus-resume-alsa-info.log)

**Comment by chih-canonical** [comment]
@snake0x65 FYI. We are using Dell Bullseye (also in Intel and AMD variants) as the reference platforms. And we had worked on Dell Cyborg before and there should not be much difference between these two platforms. If possible, can you try our patched kernel in the PPA on your Dell hardware please?

**Comment by snake0x65** [comment]
Thanks, I can see files now. After suspend() all transactions on I2C bus from cs8409 to cs42l42 failing. This is the reason for "no audio" issue.  We will investigate this issue, but we do not have same failure on CYBORG variants. It is something platform specific. The failure on the platform after suspend() is shown below:
107.027265] snd_hda_codec_cirrus hdaudioC0D0: cs8409_i2c_read() 0x90 : 0x130f = 0x0c
[  107.035269] snd_hda_codec_cirrus hdaudioC0D0: cs8409_i2c_read() 0x90 : 0x1b7b = 0x00
[  107.043202] snd_hda_codec_cirrus hdaudioC0D0: cs8409_i2c_read() 0x90 : 0x130f = 0x0c
[  107.051201] snd_hda_codec_cirrus hdaudioC0D0: cs8409_i2c_read() 0x90 : 0x1308 = 0x00
[  107.051204] snd_hda_codec_cirrus hdaudioC0D0: cs8409_jack_unsol_event() HSDET_AUTO_DONE: TYPE = 1
[  107.051206] snd_hda_codec_cirrus hdaudioC0D0: cs8409_jack_unsol_event() Jack status has changed
[  107.068570] snd_hda_codec_cirrus hdaudioC0D0: cs8409_jack_unsol_event() HP: Plugged, MIC: Plugged
[  107.068576] snd_hda_codec_cirrus hdaudioC0D0: cs8409_jack_unsol_event() gpio4=00000010
[  107.068577] snd_hda_codec_cirrus hdaudioC0D0: cs8409_set_power_mode()
[  107.068663] snd_hda_codec_cirrus hdaudioC0D0: cs8409_jack_unsol_event()
[  124.536074] wlp0s20f3: deauthenticating from a4:56:30:be:51:10 by local choice (Reason: 3=DEAUTH_LEAVING)
[  129.569684] PM: suspend entry (deep)
**[  130.010721] snd_hda_codec_cirrus hdaudioC0D0: cs8409_suspend()**

**[  131.868683] snd_hda_codec_cirrus hdaudioC0D0: cs8409_i2c_wait_complete() i2c transaction failed
[  131.869386] thermal thermal_zone4: failed to read out thermal zone (-61)
[  131.888717] snd_hda_codec_cirrus hdaudioC0D0: cs8409_i2c_wait_complete() i2c transaction failed
[  131.888994] snd_hda_codec_cirrus hdaudioC0D0: cs8409_i2c_write() 0x90 0x2302: 0x3f 1
[  131.908695] snd_hda_codec_cirrus hdaudioC0D0: cs8409_i2c_wait_complete() i2c transaction failed
[  131.911342] PM: suspend exit
[  131.928697] snd_hda_codec_cirrus hdaudioC0D0: cs8409_i2c_wait_complete() i2c transaction failed**
[  131.928955] snd_hda_codec_cirrus hdaudioC0D0: cs8409_i2c_write() 0x90 0x1101: 0xfe 1

**Comment by snake0x65** [comment]
Could you, please send me the link to your patched kernel for Cyborg AMD variant. Also what is kernel version on your build. We are using 5.10.7 at the moment. I feel like there is no difference in HDA framework between 5.10.0 and 5.10.7.

**Comment by chih-canonical** [comment]
Yes, please refer to https://launchpad.net/~vicamo/+archive/ubuntu/ppa-1913523 about applying our patched kernel.

**Comment by snake0x65** [comment]
Thanks a lot, I will try with your kernel.

**Comment by snake0x65** [comment]
With your patched kernel:
**vitaly@vitaly-Inspiron-5415:~ uname -a
Linux vitaly-Inspiron-5415 5.10.0-2014-oem #15+lp1913523.cirrus.CS8409.CS42L42.3-Ubuntu SMP Tue Feb 23 03:2 x86_64 x86_64 x86_64 GNU/Linux
vitaly@vitaly-Inspiron-5415:~**

All audio functions working OK, no issue observed so far on my AMD Cyborg platform. I did several suspend/resume circles and no I2C transaction failure. Please, see dmesg.log attached.
[dmesg.log](https://github.com/CirrusLogic/product-support/files/6028107/dmesg.log)

**Comment by chih-canonical** [comment]
@snake0x65 Just heard from Dell that the issue is suspected to be caused by the lacking RTD3 support when system resumes from s2i (suspend-to-idle.) And even on Win10, because of the lack of RTD3 support, it will turn into BSOD when the system goes to modern standby. 

Your Cyborg AMD is not affected because it is running on the legacy S3 mode.

**Comment by snake0x65** [comment]
Understood. So just waiting for Dell to investigate RTD3 issue. Please, let us know. By the way we might be getting Bullseye platform soon, so testing will be  more consistent.

**Comment by sunnycrown83** [comment]
Just clarify, the RTD3 requires Cirrus to confirm if it's ready under Linux. I believe at beginning we requested RTD3 because the sleep mode on Bullseye TGL is S2I. @chih-canonical BTW, as you said you still saw the resuming issue on Bullseye ICL, however on Bullseye ICL, the sleep mode is legacy S3 as well. So we can't confirm this issue doesn't happen on legacy S3.

**Comment by chih-canonical** [comment]
@snake0x65 @sunnycrown83 was right and sorry for the misinformation given in my comments earlier. Our Bullseye ICL is indeed also running on legacy S3 and still sees this issue. Please continue debugging it according to the provided info. 

@sunnycrown83 can we speed up the delivery of a Bullseye ICL or TGL samples to CirrusLogic team please?

**Comment by hhyshw** [comment]
“Just heard from Dell that the issue is suspected to be caused by the lacking RTD3 support when system resumes from s2i (suspend-to-idle.) And even on Win10, because of the lack of RTD3 support, it will turn into BSOD when the system goes to modern standby.
@chih-canonical Modern standby is windows 10 behavior . From my understanding , the Cyborg AMD and Intel both enable Modern standby at BIOS indeed .  I don't think it will affect the test. @sunnycrown83  Would you help to clarify the difference for me between TGL is S2I and RTD3 ?
@snake0x65 Do you have received the Bullseye TGL from KC yet ?

**Comment by snake0x65** [comment]
@hhyshw Yes, Karl, Bullseye  TGL platform was delivered yesterday. Will build and test today.

**Comment by snake0x65** [comment]
Hi, I have setted up bullseye platform with our 5.10.7 kernel and the latest driver. I cannot see audio issues so far. It suspends and resumes with no audio lost. All functions working correctly. Please see attached dmesg.log file for your reference. 
Linux cirrus-Vostro-3500 5.10.7+ #1 SMP Sat Feb 13 14:47:51 GMT 2021 x86_64 x86_64 x86_64 GNU/Linux 
[dmesg.log](https://github.com/CirrusLogic/product-support/files/6035996/dmesg.log)
Please, note this kernel is built on DELL Cyborg platform with all default settings in .config file.
I will download and install Canonical  https://launchpad.net/~vicamo/+archive/ubuntu/ppa-1913523 and double check.

**Comment by snake0x65** [comment]
Tested with: Linux cirrus-Vostro-3500 5.10.0-2014-oem #15+lp1913523.cirrus.CS8409.CS42L42.3-Ubuntu SMP Tue Feb 23 03:2 x86_64 x86_64 x86_64 GNU/Linux kernel, Canonical https://launchpad.net/~vicamo/+archive/ubuntu/ppa-1913523
No issues with suspend/resume , please see log attached:
[dmesg.log](https://github.com/CirrusLogic/product-support/files/6036142/dmesg.log)
I have tried few options: suspend when audio stream closed, suspend via UI button suspend. 
I cannot reproduce it. My model is DELL-BULLSEYE COMPAL TGL SSID 1028:00a24
Could you, please, share your .config file so we can build kernel with same settings. 
Do I need to enable anything in BIOS ?

**Comment by hhyshw** [comment]
@snake0x65  Thanks for kindly help. DELL-BULLSEYE COMPAL TGL should only support Modern standby although I don't think it is related to the issue.
 Can you find what 's the problem cause the I2C bus failed between codec and Reed ?
@sunnycrown83 Would you help to share the Compal test result with us here ?

**Comment by snake0x65** [comment]
@hhyshw  it looks like Reed chip is still in reset after suspend, or it was in reset and not initialised,  or maybe power was not applied  to Reed, so it cannot communicate with Levon. From logs I cannot find out that, as I can't read cs42l42 status and registers at that time. I might make a patch with additional Reed reset/init on resume(). Will release patch on GitHub as soon as it is ready and tested.

**Comment by snake0x65** [comment]
We have some more discussions about suspend/resume functionality and we will release a patch EOD, that we think will fix an issue with I2C read/write failure. But we will relay on Canonical to test as we don't have exactly same HW here.

**Comment by snake0x65** [comment]
@chih-canonical  New patch has been submitted: patch_cirrus_24-Feb-2021.patch  , full source is also available patch_cirrus.src.tar.gz , please see Read.me for details.

**Comment by chih-canonical** [comment]
@snake0x65 Sure. We will give the patch a try and provide our feedback shortly.

**Comment by vicamo** [comment]
[alsa-info.5.10.0-2014-oem.rev4.BNI5-DVT2-C1.X02-00.after-suspend-resume.txt](https://github.com/CirrusLogic/product-support/files/6040570/alsa-info.5.10.0-2014-oem.rev4.BNI5-DVT2-C1.X02-00.after-suspend-resume.txt)
Kernel built from 24-Feb-2021 patch doesn't fix audio lost after suspend/resume on Bullseye ICL. Log attached.

**Comment by chih-canonical** [comment]
@CirrusLogic-Team, please let us know if you'd need our Bullseye ICL sample to speed up the debug process. Preferably, we'd like to ship it locally to your local members here in Taiwan.

**Comment by hhyshw** [comment]
@chih-canonical  We have DELL-BULLSEYE COMPAL TGL SSID 1028:00a24 on developing's hand and it works fine without any error.
He has suggested to share your .config file so we can build kernel with same settings earlier.

**Comment by chih-canonical** [comment]
@hhyshw, we did not see the issue in our Dell Bullseye TGL unit, either. The issue seems to be exclusive to Bullseye ICL at the moment.

**Comment by sunnycrown83** [comment]
@chih-canonical What about the AMD config, when you talk about the issue is VNP on TGL unit, 2 things want to clarify:
1. Applied the latest patch?
2. Can you confirm if the system enters S2I sucessfully?

**Comment by chih-canonical** [comment]
@sunnycrown83 we have not received the Bullseye AMD config yet.

**Comment by snake0x65** [comment]
From logs provided we can see that HDA framework has started resume() before PM: suspend exit completed (the last line in log)
We understand that this failure happening only on platforms with deep suspend, and we suspect that in deep suspend power was disconnected from CS42L42, in this case CS42L42 left in uninitialised state and cannot resume operations before full HW reset/init circle. This will result in I2C transaction failure:   0x90 : 0x1101 = 0x00 - this is cs42l42 power up command.

[  110.029063] snd_hda_codec_cirrus hdaudioC0D0: cs8409_i2c_write() Paged Transaction Failed 0x90 : 0x1101 = 0x00
[  110.049655] snd_hda_codec_cirrus hdaudioC0D0: cs8409_i2c_write() Transaction Failed 0x90 : 0x1101 = 0x00
[  110.050138] snd_hda_codec_cirrus hdaudioC0D0: cs8409_i2c_write() 0x90 0x1101: 0x02 1
[  110.257990] usb 1-6: reset high-speed USB device number 2 using xhci_hcd 
.....
[  110.443187] thermal thermal_zone4: failed to read out thermal zone (-61)
[  110.445622] snd_hda_codec_cirrus hdaudioC0D0: hda_codec_setup_stream: NID=0x2, stream=0x1, channel=0, format=0x11[  110.476979] PM: suspend exit

So, we need to add additional RESET/INIT on every resume() to fix this issue. Will make new patch and release after testing.

**Comment by hhyshw** [comment]
@snake0x65  You are right , this is my guessing . Cyborg AMD, Intel, Bullseye TGL are supporting modern Standby.  While Bullseye ICL and AMD are supporting D3.

**Comment by snake0x65** [comment]
@chih-canonical  New patch patch_cirrus_25-Feb-2021.patch has been submitted. Full source is also updated patch_cirrus.src.tar.gz . This patch will reset/initialise cs42l42 on resume(). Tested on Cyborg platform, and shows no regression.

**Comment by chih-canonical** [comment]
@snake0x65 With the patched kernel (patch_cirrus_25-Feb-2021.patch):

Here is our test result:

[BNT5-PRTS-C2.PLT-00] - Bullseye TGL

I met once audio saturated as reported in comment #23 after
suspend/resume. Cannot easily reproduce yet. Other than that, it's
generally working.
[alsa-info.5.10.0-2014-oem.rev5.BNT5-PRTS-C2.PLT-00.good-after-suspend-resume.txt](https://github.com/CirrusLogic/product-support/files/6047763/alsa-info.5.10.0-2014-oem.rev5.BNT5-PRTS-C2.PLT-00.good-after-suspend-resume.txt)


[BNI5-DVT2-C1.X02-00] - Bullseye ICL

Audio controls available after resumed, but cease to be able to produce
sounds.

[alsa-info.5.10.0-2014-oem.rev5.BNI5-DVT2-C1_X02-00.audio-silence-after-suspend-resume.txt](https://github.com/CirrusLogic/product-support/files/6047764/alsa-info.5.10.0-2014-oem.rev5.BNI5-DVT2-C1_X02-00.audio-silence-after-suspend-resume.txt)

**Comment by snake0x65** [comment]
@chih-canonical There are 2 possible issues with failure on resume()
1) CS42L42 still powered down
2) CS8409 was in deep sleep and also required re-initialisation after suspend to D3, restoring settings for GPIO and I2C bus.
Please, find  patch_cirrus_26-Feb-2021.patch, this patch should reset and initialise both cs8409 and cs42l42 on resume.
As usual patch_cirrus.src.tar.gz was updated with latest patch.

**Comment by snake0x65** [comment]
New patch patch_cirrus_27-Feb-2021.patch updated

**Comment by snake0x65** [comment]
@chih-canonical I have updated latest patch chain , please follow READ.me:
File : cirrus_patch_01_03_2021.tar.gz 

This is series of patches adding support for CS8409/CS42L42 codec.
Please unpack into your linux root directory and apply via git.

> tar xvf cirrus_patch_01_03_2021.tar.gz 
> git am *.patch

This series of patches is a candidate for upstream submission.

NOTE: You will need to set default sample rate for pulseaudio:
file: /etc/pulse/daemon.conf
default-sample-rate = 48000

Full sound/pci/hds source with latest patch also updated:
File: patch_cirrus.src.tar.gz

**Comment by hhyshw** [comment]
@sunnycrown83 @chih-canonical   Would you help to try the patch ?

**Comment by sunnycrown83** [comment]
@hhyshw Confirmed with Canonical, looks like latest patch fixed the current open issues based on engineers' sanity check.
@chih-canonical Would you please release a test kernel and to have ODM verification as well.

**Comment by chih-canonical** [comment]
The test kernel with the latest patch is available at the usual place: https://launchpad.net/~vicamo/+archive/ubuntu/ppa-1913523

**Comment by snake0x65** [comment]
@chih-canonical Please, note that you only need 4 patches for fully functional driver on Dell platforms.
patch 0005 will add support for our development platform, and patch 0006 will enable debug logging, so these last 2 patches are not mandatory.

**Comment by chih-canonical** [comment]
@snake0x65 Alright. But please let us know about the final form of those patches once they are submitted upstream.

**Comment by snake0x65** [comment]
@chih-canonical  patch chain has been comited to ALSA maintainer git: https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/   branch for-next.

b9dd23bb03fe241ccb774c59b05d5cbac07895dc ALSA: hda/cirrus: Add Headphone and Headset MIC Volume Control
b73df04187ebb52edf3f7e502bb245c5ccab2763 ALSA: hda/cirrus: Add jack detect interrupt support from CS42L42 companion codec.
6cc7e93f46a5ce9f65ad3c6c6f645f1d831a8fa4 ALSA: hda/cirrus: Add support for CS8409 HDA bridge and CS42L42 companion codec.
b95a913cb368edcb606d844a6dc6240093d87020 ALSA: hda/cirrus: Increase AUTO_CFG_MAX_INS from 8 to 18
