### ISSUE TITLE
Loud noises are heard in audio playback when doing cold boot 

### ISSUE THREAD

**Issue by chih-canonical** [CirrusLogic/product-support#4]
We once met on a cold booted from an over-night off in our Bullseye TGL sample: BNT5-PRTS-C2 PLT-00, that its audio playback carries plenty of loud noises that one would consider unusable, but mute the system and un-mute brings it back to normal. Default sampling rate already set to 48000. Attach alsa-info captured (after it return to normal). Still have no luck to reproduce this yet.

[alsa-info.txt.5.10.0-2014-oem.BNT5-PRTS-C2.txt](https://github.com/CirrusLogic/product-support/files/6040593/alsa-info.txt.5.10.0-2014-oem.BNT5-PRTS-C2.txt)

**Comment by chih-canonical** [comment]
We managed to reproduce this issue also in our Bullseye ICL sample: BNI5-DVT2-C1.X02-00. And this time it took 2 mute/unmute cycles to bring the audio back to normal (alsa-info output is also attached for your reference.)

[alsa-info.5.10.0-2014-oem.rev4.BNI5-DVT2-C1.X02-00.after-suspend-resume.txt](https://github.com/CirrusLogic/product-support/files/6040606/alsa-info.5.10.0-2014-oem.rev4.BNI5-DVT2-C1.X02-00.after-suspend-resume.txt)

**Comment by snake0x65** [comment]
@chih-canonical  From logs provided I cannot see any obvious reason for this failure. I had this issue in earlier versions of the driver, but now I cannot see it any more. I also noticed that this failure only on speakers, if you connect HP no noise on outputs. Could be AMP issue? Not sure yet. Investigating.

**Comment by hhyshw** [comment]
@snake0x65 
   Do you have the following setting available at the driver ? 
	Bullseye: single DMIC on R ch, -14 dB attenuation on DSP
	Cyborg/Warlock: stereo DMIC, 0 dB attenuation on DSP
@chih-canonical Is it possible that you can help to provide a video clip to help us that we talk with same issue ?

**Comment by snake0x65** [comment]
@hhyshw I need to check that. I was using Windows INF hw setup from cs8409_05b2.inf , I believe newer version is available now.

**Comment by hhyshw** [comment]
cs8409_05b4.inf is ready now.

**Comment by snake0x65** [comment]
Please, try to reproduce this issue with patch: patch_cirrus_25-Feb-2021.patch

**Comment by chih-canonical** [comment]
patch_cirrus_25-Feb-2021.patch is being built as version 5.10.0-2014.15+lp1913523.cirrus.CS8409.CS42L42.5 in PPA.

For video clip, please download from https://drive.google.com/file/d/1-w7HddlcC26Sz6TBxMQ4ur4OZ4uUcuxc/view?usp=sharing . DO NOT SHARE PUBLICLY. Tested on Bullseye ICL as it seems it can stably reproduce this case. Always saturated at cold boot, a warm boot would definitely cure it, and mute/unmute might work (but in the video, not), too.

**Comment by snake0x65** [comment]
@chih-canonical yes, we can see an issue here on the video. let see how it behaves with today's patch.
