### ISSUE TITLE
Input Device does not switch to Headset Mic automatically when plugged in one such device

### ISSUE THREAD

**Issue by chih-canonical** [CirrusLogic/product-support#6]
With the latest patch set (dated on 3/8), system does not switch to Headset Mic as the Input Device in Sound Settings when inserting such device.

![Screenshot from 2021-03-09 14-29-48](https://user-images.githubusercontent.com/79449749/110428637-91af0f80-80e4-11eb-908b-087a357e3aee.png)
The Input Device remains at "Microphone- Built-in Audio" when plugging in a headset device, and users have to manually switch to "Headset Microphone - Built-in Audio" in the drop-down list for the recording via headset to work.

**Comment by snake0x65** [comment]
@chih-canonical What device is used for this test? On my Inspiron-5415 I can't reproduce this issue.

**Comment by snake0x65** [comment]
@chih-canonical  could you, please run evtest and check if you are getting jack notifications from the driver? It might be an issue with UI itself.

**Comment by chih-canonical** [comment]
@snake0x65, I was using an Apple headset that came with an iPhone. evtest can detect the headset plugging-in event just fine though.

**Comment by snake0x65** [comment]
@chih-canonical  Thank you, we will re-test with Apple headset and see where driver notification is lost.

**Comment by chih-canonical** [comment]
@snake0x65 Here is our developer's feedback on this issue for your reference. 
"
switch automatically. If it is 'Mic' like lenovo+realtek codec, it will switch automatically.

Could we change the input control name to Mic for below content:

Node 0x34 [Pin Complex] wcaps 0x400001: Stereo
  Control: name="Headset Mic Capture Volume", index=0, device=0
    ControlAmp: chs=1, dir=In, idx=0, ofs=0
  Pincap 0x00000020: IN
  Pin Default 0x04a12050: [Jack] Mic at Ext Right
    Conn = 1/8, Color = Grey
    DefAssociation = 0x5, Sequence = 0x0
  Pin-ctls: 0x20: IN

 control.5 {
  iface MIXER
  name 'Headset Mic Capture Volume'
  value -4
  comment {
   access 'read write'
   type INTEGER
   count 1
   range '-97 - 12'
   dbmin -9999999
   dbmax 1200
   dbvalue.0 -400
  }
 }
"

**Comment by chih-canonical** [comment]
@snake0x65 Our developer goes on to say:
"if the audio jack has hw capability to detect plugging/unplugging, the name should be Mic

If the jack doesn't have hw capability, they will be named to headset mic phantom like other dell machines, in this case, system will pop up a dialogue box when audio jack insertion is detected to let users pick the correct device type"

**Comment by chih-canonical** [comment]
@snake0x65 FYI. here are a few examples of  "headset mic phantom" used in other Dell machines:


name 'Headset Mic Phantom Jack'
name 'Headset Mic Boost Volume'

**Comment by snake0x65** [comment]
@chih-canonical could you, please, test fix patch 0001-ALSA-hda-cirrus-Fix-Headset-Mic-volume-control-name.patch , it should fix this issue. Do we have Bug report for that ?

**Comment by chih-canonical** [comment]
@snake0x65 Not sure what you meant by "bug report"? Those bugs were reported against other OEM programs we worked on before and were mostly private.

**Comment by snake0x65** [comment]
@chih-canonical something similar to this https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1916554 , I would just put it in commit message. I just need a URI to this issue. But,  if you don't have it , then no problem, we will upstream fix as soon as you confirm that our patch has fixed an issue.

**Comment by chih-canonical** [comment]
@snake0x65 With the latest patch, when plugging a headset device, both Input Device and Output Device can now correctly switch to the headset and this is an expected behavior. We can consider this issue fixed. Thank you.

**Comment by snake0x65** [comment]
@chih-canonical Thank you. We will push this patch to upstream.

**Comment by snake0x65** [comment]
@chih-canonical New set of patches have been accepted to ALSA upstream: https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git  branch for-next.
Commits IDs are:
ALSA: hda/cirrus: Make CS8409 driver more generic by using fixups.
9f8de3b7d789693008b65a4849bc444e81fcfe5a ALSA: hda/cirrus: Fix CS42L42 Headset Mic volume control name
61a9aba19f4482984dc7ec5c04c54bf51166cff2 ALSA: hda/cirrus: Cleanup patch_cirrus.c code.
fb3447d5842b71ec960da1b8a3ca5ee5f46a5327 ALSA: hda/cirrus: Add error handling into CS8409 I2C functions
