### ISSUE TITLE
Impact of applying "default-sample-rate = 48" to non-CirrusLogic devices

### ISSUE THREAD

**Issue by chih-canonical** [CirrusLogic/product-support#7]
We have met some difficulty trying to apply the following setting globally across different audio codecs, and would like to find out from CirrusLogic if the sample rate can be configured as part of the driver?

"default-sample-rate = 48000"

**Comment by snake0x65** [comment]
@chih-canonical  we will investigate and let you know ASAP

**Comment by snake0x65** [comment]
@chih-canonical , we have a patch to fix the default-sample rate issue. we will push the patch upstream soon and let you know.

**Comment by snake0x65** [comment]
@chih-canonical , we have released new patches for platforms with CS8409/CS42L42:  https://github.com/CirrusLogic/product-support/tree/cs8409_hda/dell/hda/5.14 . One of the patches fixing the 48000 issue.  Are you involved with the testing of the dolphin platform?

**Comment by snake0x65** [comment]
@chih-canonical , new patch chain is available, and has been sent to upstream for review: https://github.com/CirrusLogic/product-support/tree/cs8409_hda/dell/hda/5.14 file https://github.com/CirrusLogic/product-support/blob/cs8409_hda/dell/hda/5.14/patch_cirrus_dolphin_v3.tar.gz

**Comment by snake0x65** [comment]
New patch set have been uploaded : https://github.com/CirrusLogic/product-support/blob/cs8409_hda/dell/hda/5.14/patch_cirrus_dolphin_v4.tar.gz , fixing dolphin boot/suspend pops issues.
