### ISSUE TITLE
The initial output volume for the built-in speaker is "100%"

### ISSUE THREAD

**Issue by chih-canonical** [CirrusLogic/product-support#8]
[Summary]
The default output volume is "100%"

[Steps to reproduce]
1. Check the default output volume

[Expected result]
The default output should be 46%

[Actual result]
The default output volume is "100%"

[Failure rate]
10/10

The issue happened to all our Bullseye units equipped with the CirrusLogic audio codec

**Comment by snake0x65** [comment]
@chih-canonical , from the description, it is not clear to us how this testing was done, could you give us instructions on how you run this test.

**Comment by snake0x65** [comment]
@chih-canonical also what is the output device? Speaker or HP ?

**Comment by chih-canonical** [comment]
＠snake0x65, first of all, here is the latest image which cn be used in both Bullseye and Warlock machines: http://162.213.32.53/mdjJOSFwx1tVX5fVEtbwdlgq/fossa-warcraft-intel/IEVF_X88/dell-bto-focal-fossa-proposed-release-X88-20210329-2.iso

This issue is about Output Device Volume for the built-in speaker being set to 100 when the image installation is completed.

(Note: Dell just told us that this issue was also found in Windows.)

**Comment by chih-canonical** [comment]
@snake0x65 please note this X88 image is missing the default-sample-rate = 48000 and it has already been added in a newer image.

**Comment by snake0x65** [comment]
@chih-canonical , we do not control speaker volume as the speaker amp is running in HW mode. So, we can't set the initial volume.

**Comment by chih-canonical** [comment]
@snake0x65 did you mean to say that this is out of the software/OS control when it comes to setting up initial speaker volume?

**Comment by snake0x65** [comment]
@chih-canonical  yes, this is what I mean. TA amp is not controlled by our driver.

**Comment by snake0x65** [comment]
@chih-canonical , do you agree  to close this ticket, it is not related to cs42l42 driver.

**Comment by chih-canonical** [comment]
@snake0x65 yes, we have no objection to that.
