### ISSUE TITLE
The initial input volume for the built-in Mic is 0% 

### ISSUE THREAD

**Issue by chih-canonical** [CirrusLogic/product-support#9]
[Summary]
The default input volume is "0%"

[Steps to reproduce]
1. Check the default input volume

[Expected result]
The default input volume is "16%"

[Actual result]
The default input volume is "0%"

[Failure rate]
10/10

It happens to all our Bullseye ICL/TGL/AMD samples with the CirrusLogic audio codec and in a freshly installed unit.

**Comment by snake0x65** [comment]
@chih-canonical , from the description, it is not clear to us how this testing was done, could you give us instructions on how you run this test.

**Comment by snake0x65** [comment]
@chih-canonical also, what is an input device? Internal mic or HS mic?

**Comment by chih-canonical** [comment]
＠snake0x65, first of all, here is the latest image which cn be used in both Bullseye and Warlock machines: http://162.213.32.53/mdjJOSFwx1tVX5fVEtbwdlgq/fossa-warcraft-intel/IEVF_X88/dell-bto-focal-fossa-proposed-release-X88-20210329-2.iso

This issue is about Input Device Volume for the built-in MIC being set to 0 when the image installation is completed.

**Comment by snake0x65** [comment]
@chih-canonical , please, find attached https://github.com/CirrusLogic/product-support/blob/cs8409_hda/dell/hda/5.10.7/0001-ALSA-hda-cirrus-Set-Initial-DMIC-volume-for-Bullseye.patch

**Comment by chih-canonical** [comment]
@snake0x65 We will give the provided patch a try and share the test result later.

**Comment by chih-canonical** [comment]
@snake0x65 A test kernel with the patch can be found in https://launchpad.net/~vicamo/+archive/ubuntu/ppa-1923557

However, it failed our verification. Here are the comments from our developer:
"
While the original patch failed to be applied on a few possible trees I know, the actual patch I use can be found in the attachment. However, it does not seem to fix this issue with following steps taken:

  1. Recovery the system
  2. After first user login, install the prebuilt kernel from https://launchpad.net/~vicamo/+archive/ubuntu/ppa-1923557
  3. Enable debug messages for snd_hda_codec_cirrus:

       echo "options snd_hda_codec_cirrus dyndbg" | \
           sudo tee /etc/modprobe.d/cirrus.conf

  4. Reboot and check amixer output. Still 0%.
  "

**Comment by stefdb** [comment]
@chih-canonical We have pushed a new patch to test: https://github.com/CirrusLogic/product-support/blob/cs8409_hda/dell/hda/5.10.7/0001-ALSA-hda-fix-initial-dmic-volume.patch

We also had some questions. Firstly, our understanding is that this issue is that on the first time after image installation, the volume is 0%, however, in the test steps above, it looks like the system is booted once, then the patch kernel is installed, and retested. Is it possible that the 0% value is cached after the first boot, prior to testing the updated kernel, with that value restored by the UI after the system boots with the new kernel?

In addition, the reason that the original patch failed to apply initially, is because upstream has been updated, and our patch is on top of that, this may cause some issues.

**Comment by chih-canonical** [comment]
@stefdb You have made a very good point and I will highlight it internally to make sure the test steps are accurate.

**Comment by vicamo** [comment]
One comment was missing after https://github.com/CirrusLogic/product-support/issues/9#issuecomment-818600098. Basically we added following steps before a new test run without executing a full recovery again:
* shutdown the device
* boot with a liveCD
* remove `~/.config/pulse` and `/var/lib/alsa/asound.state`

**Comment by chih-canonical** [comment]
@stefdb 

Verified this revision works and initial volume set to 40%. Prebuilt kernel is in https://launchpad.net/~vicamo/+archive/ubuntu/ppa-1923557, version 5.10.0-2021.22+lp1923557.2.initial.input.vol.

Do you plan to upstream this patch? Please share the link to the commit when it is done. Thank you.

**Comment by snake0x65** [comment]
@chih-canonical , yes we have a plan to upstream, will let you know ASAP

**Comment by snake0x65** [comment]
@chih-canonical , fix patch has been submitted for upstream review.

**Comment by snake0x65** [comment]
@chih-canonical patch upstreamed : https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/commit/?id=0e853a9c3937caa9f13fdde547d6202f92457c2b

**Comment by chih-canonical** [comment]
@snake0x65 The fix is also needed in Dell Warlock, can you help extend the fix to that platform please?

**Comment by snake0x65** [comment]
@chih-canonical , OK we will make a patch to fix on Warlock as well.

**Comment by snake0x65** [comment]
@chih-canonical  , do you want us to extend this for Cyborg as well?

**Comment by chih-canonical** [comment]
I believe so as this looks to be a cross-platform issue.

**Comment by chih-canonical** [comment]
@snake0x65 Again, please let us know when a revised patch is submitted upstream so that we can start integrating it into the Ubuntu kernel. Thank you.

**Comment by snake0x65** [comment]
@chih-canonical ,  patch has been submitted upstream: https://patchwork.kernel.org/project/alsa-devel/patch/20210531163754.136736-1-vitalyr@opensource.cirrus.com/

**Comment by snake0x65** [comment]
@chih-canonical , patch has been accepted by maintainer: https://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound.git/commit/?id=527ff9550682a3d08066a000435ffd8330bdd729
